# Generated by Django 3.2.11 on 2022-01-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_phonenumberotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumberotp',
            name='phone_number',
            field=models.CharField(default=1, max_length=15, unique=True, verbose_name='phone number'),
            preserve_default=False,
        ),
    ]
