# Generated by Django 4.0 on 2022-01-24 20:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_phonenumberotp_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUserEmail',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('otp', models.CharField(max_length=6, verbose_name='otp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_user_email', to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
