# Generated by Django 3.2.11 on 2022-01-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_tempuseremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumberotp',
            name='otp',
            field=models.CharField(default='', max_length=6, verbose_name='otp'),
        ),
    ]
