# Generated by Django 4.0 on 2022-01-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_phonenumberotp_otp_phonenumberotp_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumberotp',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='phone number'),
        ),
    ]
