# Generated by Django 4.0 on 2022-01-30 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_deals', '0002_rename_bathroom_propertyhouse_bathrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyhouse',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_deals.property'),
        ),
        migrations.AlterField(
            model_name='propertyplot',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_deals.property'),
        ),
    ]
