# Generated by Django 4.0 on 2022-01-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_deals', '0003_alter_propertyhouse_property_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('plot', 'Plot'), ('commercial', 'Commercial')], max_length=50),
        ),
    ]
