# Generated by Django 4.0 on 2022-01-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_deals', '0005_alter_property_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='purpose',
            field=models.CharField(choices=[('SALE', 'Sale'), ('REQUIRED', 'Required'), ('RENT', 'Rent')], max_length=50),
        ),
    ]
