# Generated by Django 4.0 on 2022-01-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_deals', '0006_alter_property_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='purpose',
            field=models.CharField(choices=[('sale', 'Sale'), ('required', 'Required'), ('rent', 'Rent')], max_length=50),
        ),
    ]
