# Generated by Django 3.2.11 on 2022-02-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_deals', '0007_alter_property_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='unit',
        ),
        migrations.AlterField(
            model_name='property',
            name='marla',
            field=models.IntegerField(max_length=5),
        ),
    ]
