# Generated by Django 3.2.11 on 2022-02-03 06:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_deals', '0008_auto_20220202_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyComercial',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('series_from', models.CharField(max_length=150)),
                ('series_to', models.CharField(max_length=150)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_deals.property')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
