# Generated by Django 3.2.7 on 2022-02-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_deals', '0010_auto_20220227_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertycomercial',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertycomercial',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
