# Generated by Django 3.2.7 on 2022-03-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_deals', '0011_auto_20220227_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='total_price',
            new_name='from_price',
        ),
        migrations.AddField(
            model_name='property',
            name='to_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=15),
            preserve_default=False,
        ),
    ]
