# Generated by Django 3.2.7 on 2022-03-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_deals', '0014_auto_20220302_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=15, null=True),
        ),
    ]
